import { SurahMeta, CuratedVerse } from './types';

// Complete verified 114 Surahs metadata in standard Indonesian Kemenag indexing
export const SURAH_LIST: SurahMeta[] = [
  { nomor: 1, nama: "الفاتحة", namaLatin: "Al-Fatihah", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Pembukaan", deskripsi: "Surah pembuka Al-Qur'an yang agung, ummul kitab." },
  { nomor: 2, nama: "البقرة", namaLatin: "Al-Baqarah", jumlahAyat: 286, tempatTurun: "Madinah", arti: "Sapi Betina", deskripsi: "Surah terpanjang yang memuat petunjuk kehidupan lengkap." },
  { nomor: 3, nama: "آل عمران", namaLatin: "Ali 'Imran", jumlahAyat: 200, tempatTurun: "Madinah", arti: "Keluarga Imran", deskripsi: "Pelajaran tentang keteguhan iman dan pertolongan Allah." },
  { nomor: 4, nama: "النساء", namaLatin: "An-Nisa'", jumlahAyat: 176, tempatTurun: "Madinah", arti: "Wanita", deskripsi: "Hukum keluarga, keadilan, dan perlindungan kaum lemah." },
  { nomor: 5, nama: "المائدة", namaLatin: "Al-Ma'idah", jumlahAyat: 120, tempatTurun: "Madinah", arti: "Hidangan", deskripsi: "Penyempurnaan syariat dan pemenuhan janji." },
  { nomor: 6, nama: "الأنعام", namaLatin: "Al-An'am", jumlahAyat: 165, tempatTurun: "Mekah", arti: "Binatang Ternak", deskripsi: "Ketauhidan, tanda-tanda kebesaran ciptaan Allah." },
  { nomor: 7, nama: "الأعراف", namaLatin: "Al-A'raf", jumlahAyat: 206, tempatTurun: "Mekah", arti: "Tempat Tertinggi", deskripsi: "Kisah para nabi dan pengingat akhirat." },
  { nomor: 8, nama: "الأنفال", namaLatin: "Al-Anfal", jumlahAyat: 75, tempatTurun: "Madinah", arti: "Rampasan Perang", deskripsi: "Tawakal, ketaatan, dan ketenangan hati saat ujian." },
  { nomor: 9, nama: "التوبة", namaLatin: "At-Taubah", jumlahAyat: 129, tempatTurun: "Madinah", arti: "Pengampunan", deskripsi: "Pintu taubat dan kasih sayang Allah bagi yang kembali." },
  { nomor: 10, nama: "يونس", namaLatin: "Yunus", jumlahAyat: 109, tempatTurun: "Mekah", arti: "Nabi Yunus", deskripsi: "Kisah doa dan keselamatan di saat keputusasaan." },
  { nomor: 11, nama: "هود", namaLatin: "Hud", jumlahAyat: 123, tempatTurun: "Mekah", arti: "Nabi Hud", deskripsi: "Keteguhan para rasul dalam menghadapi penolakan." },
  { nomor: 12, nama: "يوسف", namaLatin: "Yusuf", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Nabi Yusuf", deskripsi: "Kisah terindah tentang kesabaran berbuah kebahagiaan." },
  { nomor: 13, nama: "الرعد", namaLatin: "Ar-Ra'd", jumlahAyat: 43, tempatTurun: "Madinah", arti: "Guruh", deskripsi: "Mengingat Allah adalah penenteram segala hati yang gundah." },
  { nomor: 14, nama: "إبراهيم", namaLatin: "Ibrahim", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Nabi Ibrahim", deskripsi: "Rasa syukur yang menambah nikmat dan keindahan iman." },
  { nomor: 15, nama: "الحجر", namaLatin: "Al-Hijr", jumlahAyat: 99, tempatTurun: "Mekah", arti: "Gunung Al-Hijr", deskripsi: "Pemeliharaan wahyu dan penghiburan bagi Nabi." },
  { nomor: 16, nama: "النحل", namaLatin: "An-Nahl", jumlahAyat: 128, tempatTurun: "Mekah", arti: "Lebah", deskripsi: "Rincian limpahan nikmat Allah di alam semesta." },
  { nomor: 17, nama: "الإسراء", namaLatin: "Al-Isra'", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Perjalanan Malam", deskripsi: "Perjalanan agung Isra Mi'raj dan adab kepada sesama." },
  { nomor: 18, nama: "الكهف", namaLatin: "Al-Kahf", jumlahAyat: 110, tempatTurun: "Mekah", arti: "Gua", deskripsi: "Cahaya pelindung fitnah dan pelajaran hikmah hidup." },
  { nomor: 19, nama: "مريم", namaLatin: "Maryam", jumlahAyat: 98, tempatTurun: "Mekah", arti: "Maryam", deskripsi: "Kasih sayang Ar-Rahman dan keajaiban doa di kala mustahil." },
  { nomor: 20, nama: "طه", namaLatin: "Thaha", jumlahAyat: 135, tempatTurun: "Mekah", arti: "Thaha", deskripsi: "Al-Qur'an diturunkan bukan untuk menyusahkanmu." },
  { nomor: 21, nama: "الأنبياء", namaLatin: "Al-Anbiya'", jumlahAyat: 112, tempatTurun: "Mekah", arti: "Para Nabi", deskripsi: "Doa-doa agung para nabi saat dirundung derita." },
  { nomor: 22, nama: "الحج", namaLatin: "Al-Hajj", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Haji", deskripsi: "Ketaatan, pengorbanan, dan persatuan umat manusia." },
  { nomor: 23, nama: "المؤمنون", namaLatin: "Al-Mu'minun", jumlahAyat: 118, tempatTurun: "Mekah", arti: "Orang-Orang Mukmin", deskripsi: "Ciri-ciri insan yang meraih ketenangan sejati." },
  { nomor: 24, nama: "النور", namaLatin: "An-Nur", jumlahAyat: 64, tempatTurun: "Madinah", arti: "Cahaya", deskripsi: "Cahaya di atas cahaya, kesucian keluarga dan kehormatan." },
  { nomor: 25, nama: "الفرقان", namaLatin: "Al-Furqan", jumlahAyat: 77, tempatTurun: "Mekah", arti: "Pembeda", deskripsi: "Doa pasangan dan penyejuk mata (Qurrata A'yun)." },
  { nomor: 26, nama: "الشعراء", namaLatin: "Asy-Syu'ara'", jumlahAyat: 227, tempatTurun: "Mekah", arti: "Para Penyair", deskripsi: "Kebenaran risalah ilahi di atas kata-kata manusia." },
  { nomor: 27, nama: "النمل", namaLatin: "An-Naml", jumlahAyat: 93, tempatTurun: "Mekah", arti: "Semut", deskripsi: "Kisah Nabi Sulaiman dan doa mensyukuri nikmat luar biasa." },
  { nomor: 28, nama: "القصص", namaLatin: "Al-Qasas", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Cerita-Cerita", deskripsi: "Pertolongan Allah bagi yang terzalimi dan lemah." },
  { nomor: 29, nama: "العنكبوت", namaLatin: "Al-'Ankabut", jumlahAyat: 69, tempatTurun: "Mekah", arti: "Laba-Laba", deskripsi: "Ujian hidup adalah kepastian untuk menguatkan keimanan." },
  { nomor: 30, nama: "الروم", namaLatin: "Ar-Rum", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Bangsa Romawi", deskripsi: "Cinta, ketenangan (sakinah), dan kasih sayang." },
  { nomor: 31, nama: "لقمان", namaLatin: "Luqman", jumlahAyat: 34, tempatTurun: "Mekah", arti: "Keluarga Luqman", deskripsi: "Nasihat penuh kelembutan seorang ayah kepada anaknya." },
  { nomor: 32, nama: "السجدة", namaLatin: "As-Sajdah", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Sujud", deskripsi: "Kerendahan hati bersujud di keheningan malam." },
  { nomor: 33, nama: "الأحزاب", namaLatin: "Al-Ahzab", jumlahAyat: 73, tempatTurun: "Madinah", arti: "Golongan yang Bersekutu", deskripsi: "Keteladanan mulia Rasulullah SAW dan tawakal total." },
  { nomor: 34, nama: "سبأ", namaLatin: "Saba'", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Kaum Saba'", deskripsi: "Pentingnya rasa syukur dan bahaya kesombongan." },
  { nomor: 35, nama: "فاطر", namaLatin: "Fatir", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Pencipta", deskripsi: "Maha Pencipta langit dan bumi, Pembuka pintu rahmat." },
  { nomor: 36, nama: "يس", namaLatin: "Yasin", jumlahAyat: 83, tempatTurun: "Mekah", arti: "Yasin", deskripsi: "Jantung Al-Qur'an yang membawa kedamaian jiwa." },
  { nomor: 37, nama: "الصافات", namaLatin: "As-Saffat", jumlahAyat: 182, tempatTurun: "Mekah", arti: "Barisan-Barisan", deskripsi: "Kesetiaan para nabi dalam mengemban amanah." },
  { nomor: 38, nama: "ص", namaLatin: "Sad", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Sad", deskripsi: "Kesabaran Nabi Ayyub saat menghadapi cobaan fisik." },
  { nomor: 39, nama: "الزمر", namaLatin: "Az-Zumar", jumlahAyat: 75, tempatTurun: "Mekah", arti: "Rombongan", deskripsi: "Jangan pernah berputus asa dari rahmat Allah." },
  { nomor: 40, nama: "غافر", namaLatin: "Ghafir", jumlahAyat: 85, tempatTurun: "Mekah", arti: "Maha Pengampun", deskripsi: "Berdoalah kepada-Ku, niscaya akan Kuperkenankan bagimu." },
  { nomor: 41, nama: "فصلت", namaLatin: "Fussilat", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Yang Dijelaskan", deskripsi: "Balaslah keburukan dengan kebaikan yang lebih baik." },
  { nomor: 42, nama: "الشورى", namaLatin: "Asy-Syura", jumlahAyat: 53, tempatTurun: "Mekah", arti: "Musyawarah", deskripsi: "Kebijaksanaan, pemaafan, dan keadilan musyawarah." },
  { nomor: 43, nama: "الزخرف", namaLatin: "Az-Zukhruf", jumlahAyat: 89, tempatTurun: "Mekah", arti: "Perhiasan", deskripsi: "Hakikat kebahagiaan sejati melebihi kilau duniawi." },
  { nomor: 44, nama: "الدخان", namaLatin: "Ad-Dukhan", jumlahAyat: 59, tempatTurun: "Mekah", arti: "Kabut", deskripsi: "Malam kemuliaan yang penuh berkah." },
  { nomor: 45, nama: "الجاثية", namaLatin: "Al-Jasiyah", jumlahAyat: 37, tempatTurun: "Mekah", arti: "Yang Berlutut", deskripsi: "Tanda-tanda keagungan Allah di sekeliling kita." },
  { nomor: 46, nama: "الأحقاف", namaLatin: "Al-Ahqaf", jumlahAyat: 35, tempatTurun: "Mekah", arti: "Bukit-Bukit Pasir", deskripsi: "Bakti kepada kedua orang tua dan doa kedewasaan." },
  { nomor: 47, nama: "محمد", namaLatin: "Muhammad", jumlahAyat: 38, tempatTurun: "Madinah", arti: "Nabi Muhammad", deskripsi: "Ketenangan dan kedamaian hati bagi orang beriman." },
  { nomor: 48, nama: "الفتح", namaLatin: "Al-Fath", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Kemenangan", deskripsi: "Allah yang menurunkan ketenangan ke dalam hati orang mukmin." },
  { nomor: 49, nama: "الحجرات", namaLatin: "Al-Hujurat", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Kamar-Kamar", deskripsi: "Akhlak persaudaraan, persatuan, dan prasangka baik." },
  { nomor: 50, nama: "ق", namaLatin: "Qaf", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Qaf", deskripsi: "Allah lebih dekat kepadamu daripada urat lehermu." },
  { nomor: 51, nama: "الذاريات", namaLatin: "Az-Zariyat", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Angin yang Menerbangkan", deskripsi: "Rezeki dan janji Allah di langit adalah kepastian." },
  { nomor: 52, nama: "الطور", namaLatin: "At-Tur", jumlahAyat: 49, tempatTurun: "Mekah", arti: "Bukit", deskripsi: "Bersabarlah, karena sungguh engkau berada dalam pengawasan Kami." },
  { nomor: 53, nama: "النجم", namaLatin: "An-Najm", jumlahAyat: 62, tempatTurun: "Mekah", arti: "Bintang", deskripsi: "Dan bahwasanya manusia hanya memperoleh apa yang diusahakannya." },
  { nomor: 54, nama: "القمر", namaLatin: "Al-Qamar", jumlahAyat: 55, tempatTurun: "Mekah", arti: "Bulan", deskripsi: "Al-Qur'an dimudahkan untuk menjadi pengingat." },
  { nomor: 55, nama: "الرحمن", namaLatin: "Ar-Rahman", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Maha Pengasih", deskripsi: "Maka nikmat Tuhanmu yang manakah yang kamu dustakan?" },
  { nomor: 56, nama: "الواقعة", namaLatin: "Al-Waqi'ah", jumlahAyat: 96, tempatTurun: "Mekah", arti: "Hari Kiamat", deskripsi: "Kemuliaan, pembuka keberkahan dan rezeki." },
  { nomor: 57, nama: "الحديد", namaLatin: "Al-Hadid", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Besi", deskripsi: "Dan Dia bersama kalian di mana pun kalian berada." },
  { nomor: 58, nama: "المجادلة", namaLatin: "Al-Mujadilah", jumlahAyat: 22, tempatTurun: "Madinah", arti: "Gugatan", deskripsi: "Allah mendengar keluh kesah dan pembicaraan rahasiamu." },
  { nomor: 59, nama: "الحشر", namaLatin: "Al-Hasyr", jumlahAyat: 24, tempatTurun: "Madinah", arti: "Pengusiran", deskripsi: "Nama-nama terindah Allah (Asmaul Husna)." },
  { nomor: 60, nama: "الممتحنة", namaLatin: "Al-Mumtahanah", jumlahAyat: 13, tempatTurun: "Madinah", arti: "Wanita yang Diuji", deskripsi: "Keteguhan prinsip dalam kebaikan dan keadilan." },
  { nomor: 61, nama: "الصف", namaLatin: "As-Saff", jumlahAyat: 14, tempatTurun: "Madinah", arti: "Barisan", deskripsi: "Kesesuaian antara ucapan dan perbuatan mulia." },
  { nomor: 62, nama: "الجمعة", namaLatin: "Al-Jumu'ah", jumlahAyat: 11, tempatTurun: "Madinah", arti: "Hari Jumat", deskripsi: "Panggilan ibadah dan menuntut keberkahan hidup." },
  { nomor: 63, nama: "المنافقون", namaLatin: "Al-Munafiqun", jumlahAyat: 11, tempatTurun: "Madinah", arti: "Orang Munafik", deskripsi: "Kejujuran hati dan jangan lalai karena harta." },
  { nomor: 64, nama: "التغابن", namaLatin: "At-Tagabun", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Hari Ditampakkan Kesalahan", deskripsi: "Tawakal sejati dan memaafkan kesalahan sesama." },
  { nomor: 65, nama: "الطلاق", namaLatin: "At-Talaq", jumlahAyat: 12, tempatTurun: "Madinah", arti: "Talak", deskripsi: "Barang siapa bertakwa, Allah beri jalan keluar dan rezeki tak terduga." },
  { nomor: 66, nama: "التحريم", namaLatin: "At-Tahrim", jumlahAyat: 12, tempatTurun: "Madinah", arti: "Pengharaman", deskripsi: "Taubat nasuha dan kehangatan menjaga keluarga." },
  { nomor: 67, nama: "الملك", namaLatin: "Al-Mulk", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Kerajaan", deskripsi: "Surah pelindung yang membawa kedamaian dan syafaat." },
  { nomor: 68, nama: "القلم", namaLatin: "Al-Qalam", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Pena", deskripsi: "Akhlak yang agung dan kesabaran menanti ketetapan." },
  { nomor: 69, nama: "الحاقة", namaLatin: "Al-Haqqah", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Hari Kiamat", deskripsi: "Kepastian hari akhir dan kejujuran kitab amalan." },
  { nomor: 70, nama: "المعارج", namaLatin: "Al-Ma'arij", jumlahAyat: 44, tempatTurun: "Mekah", arti: "Tempat Naik", deskripsi: "Maka bersabarlah engkau dengan kesabaran yang indah." },
  { nomor: 71, nama: "نوح", namaLatin: "Nuh", jumlahAyat: 28, tempatTurun: "Mekah", arti: "Nabi Nuh", deskripsi: "Istighfar yang membuka pintu rezeki dan hujan keberkahan." },
  { nomor: 72, nama: "الجن", namaLatin: "Al-Jinn", jumlahAyat: 28, tempatTurun: "Mekah", arti: "Jin", deskripsi: "Ketundukan pada petunjuk Al-Qur'an yang menakjubkan." },
  { nomor: 73, nama: "المزمل", namaLatin: "Al-Muzzammil", jumlahAyat: 20, tempatTurun: "Mekah", arti: "Orang yang Berselimut", deskripsi: "Ketenangan bangun di sepertiga malam untuk bermunajat." },
  { nomor: 74, nama: "المدثر", namaLatin: "Al-Muddassir", jumlahAyat: 56, tempatTurun: "Mekah", arti: "Orang yang Berkemul", deskripsi: "Bangkitlah dan sebarkan kebaikan dengan penuh kesucian." },
  { nomor: 75, nama: "القيامة", namaLatin: "Al-Qiyamah", jumlahAyat: 40, tempatTurun: "Mekah", arti: "Hari Kiamat", deskripsi: "Jiwa yang selalu mencela diri demi perbaikan." },
  { nomor: 76, nama: "الإنسان", namaLatin: "Al-Insan", jumlahAyat: 31, tempatTurun: "Madinah", arti: "Manusia", deskripsi: "Ketulusan memberi makan karena mencari keridhaan Allah semata." },
  { nomor: 77, nama: "المرسلات", namaLatin: "Al-Mursalat", jumlahAyat: 50, tempatTurun: "Mekah", arti: "Malaikat yang Diutus", deskripsi: "Tanda-tanda kepastian janji Allah di alam semesta." },
  { nomor: 78, nama: "النبأ", namaLatin: "An-Naba'", jumlahAyat: 40, tempatTurun: "Mekah", arti: "Berita Besar", deskripsi: "Awal juz 'Amma tentang penciptaan tidur sebagai istirahat." },
  { nomor: 79, nama: "النازعات", namaLatin: "An-Nazi'at", jumlahAyat: 46, tempatTurun: "Mekah", arti: "Malaikat Pencabut", deskripsi: "Keagungan ciptaan langit dan bumi penenang jiwa." },
  { nomor: 80, nama: "عبس", namaLatin: "Abasa", jumlahAyat: 42, tempatTurun: "Mekah", arti: "Bermuka Masam", deskripsi: "Kemuliaan setiap insan dan kerendahan hati." },
  { nomor: 81, nama: "التكوير", namaLatin: "At-Takwir", jumlahAyat: 29, tempatTurun: "Mekah", arti: "Menggulung", deskripsi: "Dan fajar apabila telah menyingsing membawa harapan baru." },
  { nomor: 82, nama: "الانفطار", namaLatin: "Al-Infitar", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Terbelah", deskripsi: "Wahai manusia, apa yang memperdayakanmu dari Tuhanmu yang Maha Pemurah?" },
  { nomor: 83, nama: "المطففين", namaLatin: "Al-Mutaffifin", jumlahAyat: 36, tempatTurun: "Mekah", arti: "Orang-Orang Curang", deskripsi: "Kejujuran dan mata air kesegaran di surga." },
  { nomor: 84, nama: "الانشقاق", namaLatin: "Al-Insyiqaq", jumlahAyat: 25, tempatTurun: "Mekah", arti: "Terbelah", deskripsi: "Perjalanan manusia kembali menuju Tuhannya." },
  { nomor: 85, nama: "البروج", namaLatin: "Al-Buruj", jumlahAyat: 22, tempatTurun: "Mekah", arti: "Gugusan Bintang", deskripsi: "Keteguhan hati orang-orang beriman saat ditindas." },
  { nomor: 86, nama: "الطارق", namaLatin: "At-Tariq", jumlahAyat: 17, tempatTurun: "Mekah", arti: "Yang Datang di Malam Hari", deskripsi: "Setiap jiwa memiliki penjaga dan pemelihara dari Allah." },
  { nomor: 87, nama: "الأعلى", namaLatin: "Al-A'la", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Maha Tinggi", deskripsi: "Sucikan nama Tuhanmu, Dia yang menciptakan dan menyempurnakan." },
  { nomor: 88, nama: "الغاشية", namaLatin: "Al-Ghasyiyah", jumlahAyat: 26, tempatTurun: "Mekah", arti: "Hari Pembalasan", deskripsi: "Kesejukan surga dan renungan pada indahnya ciptaan." },
  { nomor: 89, nama: "الفجر", namaLatin: "Al-Fajr", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Fajar", deskripsi: "Wahai jiwa yang tenang, kembalilah kepada Tuhanmu dengan ridha." },
  { nomor: 90, nama: "البلد", namaLatin: "Al-Balad", jumlahAyat: 20, tempatTurun: "Mekah", arti: "Negeri", deskripsi: "Saling berpesan untuk bersabar dan saling berkasih sayang." },
  { nomor: 91, nama: "الشمس", namaLatin: "Asy-Syams", jumlahAyat: 15, tempatTurun: "Mekah", arti: "Matahari", deskripsi: "Sungguh beruntung orang yang menyucikan jiwanya." },
  { nomor: 92, nama: "الليل", namaLatin: "Al-Lail", jumlahAyat: 21, tempatTurun: "Mekah", arti: "Malam", deskripsi: "Barang siapa memberi dan bertakwa, Kami mudahkan baginya jalan kebahagiaan." },
  { nomor: 93, nama: "الضحى", namaLatin: "Ad-Duha", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Waktu Duha", deskripsi: "Tuhanmu tidak meninggalkanmu dan tidak pula membencimu." },
  { nomor: 94, nama: "الشرح", namaLatin: "Al-Insyirah", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Kelapangan", deskripsi: "Maka sesungguhnya bersama kesulitan ada kemudahan." },
  { nomor: 95, nama: "التين", namaLatin: "At-Tin", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Buah Tin", deskripsi: "Manusia diciptakan dalam bentuk yang sebaik-baiknya." },
  { nomor: 96, nama: "العلق", namaLatin: "Al-'Alaq", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Segumpal Darah", deskripsi: "Bacalah dengan menyebut nama Tuhanmu yang menciptakan." },
  { nomor: 97, nama: "القدر", namaLatin: "Al-Qadr", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Kemuliaan", deskripsi: "Malam yang lebih baik daripada seribu bulan penuh kedamaian." },
  { nomor: 98, nama: "البينة", namaLatin: "Al-Bayyinah", jumlahAyat: 8, tempatTurun: "Madinah", arti: "Bukti Nyata", deskripsi: "Ikhlas dalam beragama dan sebaik-baik makhluk." },
  { nomor: 99, nama: "الزلزلة", namaLatin: "Az-Zalzalah", jumlahAyat: 8, tempatTurun: "Madinah", arti: "Goncangan", deskripsi: "Sekecil apa pun kebaikan akan tampak balasannya." },
  { nomor: 100, nama: "العاديات", namaLatin: "Al-'Adiyat", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Kuda Perang", deskripsi: "Kesetiaan dan pengingat hakikat syukur." },
  { nomor: 101, nama: "القارعة", namaLatin: "Al-Qari'ah", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Hari Kiamat", deskripsi: "Timbangan amalan yang membawa kehidupan yang diridhai." },
  { nomor: 102, nama: "التكاثر", namaLatin: "At-Takasur", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Bermegah-Megahan", deskripsi: "Ketenangan batin melampaui perlombaan harta dunia." },
  { nomor: 103, nama: "العصر", namaLatin: "Al-'Asr", jumlahAyat: 3, tempatTurun: "Mekah", arti: "Masa", deskripsi: "Saling menasihati dalam kebenaran dan kesabaran." },
  { nomor: 104, nama: "الهمزة", namaLatin: "Al-Humazah", jumlahAyat: 9, tempatTurun: "Mekah", arti: "Pengumpat", deskripsi: "Menjaga lisan dan hati dari menyakiti sesama." },
  { nomor: 105, nama: "الفيل", namaLatin: "Al-Fil", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Gajah", deskripsi: "Perlindungan Allah terhadap rumah-Nya yang suci." },
  { nomor: 106, nama: "قريش", namaLatin: "Quraisy", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Suku Quraisy", deskripsi: "Rasa aman dari ketakutan dan kecukupan dari kelaparan." },
  { nomor: 107, nama: "الماعون", namaLatin: "Al-Ma'un", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Barang Berguna", deskripsi: "Kasih sayang kepada anak yatim dan tolong-menolong." },
  { nomor: 108, nama: "الكوثر", namaLatin: "Al-Kausar", jumlahAyat: 3, tempatTurun: "Mekah", arti: "Nikmat yang Berlimpah", deskripsi: "Sungguh Kami telah memberimu telaga dan nikmat yang banyak." },
  { nomor: 109, nama: "الكافرون", namaLatin: "Al-Kafirun", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Orang Kafir", deskripsi: "Keteguhan prinsip bertoleransi: bagimu agamamu, bagiku agamaku." },
  { nomor: 110, nama: "النصر", namaLatin: "An-Nasr", jumlahAyat: 3, tempatTurun: "Madinah", arti: "Pertolongan", deskripsi: "Pertolongan Allah yang tiba dan tasbih penuh syukur." },
  { nomor: 111, nama: "المسد", namaLatin: "Al-Lahab", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Gejolak Api", deskripsi: "Keadilan bagi pembenci kebenaran." },
  { nomor: 112, nama: "الإخلاص", namaLatin: "Al-Ikhlas", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Kemurnian Keesaan Allah", deskripsi: "Katakanlah: Dialah Allah, Yang Maha Esa, tempat bergantung." },
  { nomor: 113, nama: "الفلق", namaLatin: "Al-Falaq", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Waktu Subuh", deskripsi: "Doa memohon perlindungan dari kejahatan waktu malam dan kedengkian." },
  { nomor: 114, nama: "الناس", namaLatin: "An-Nas", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Manusia", deskripsi: "Perlindungan kepada Tuhan manusia dari bisikan kecemasan di dalam dada." }
];

// Curated Heartfelt & Emotional Verses with verified Arabic Uthmani text & Kemenag Indonesian translation
export const CURATED_VERSES: CuratedVerse[] = [
  {
    id: 'curated-insyirah-5-6',
    surahNumber: 94,
    surahName: 'Al-Insyirah',
    surahArabic: 'الشرح',
    verseNumber: '5 - 6',
    arabicText: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا',
    translation: 'Maka sesungguhnya bersama kesulitan ada kemudahan. Sesungguhnya bersama kesulitan ada kemudahan.',
    themeCategory: 'ujian',
    themeLabel: 'Untuk yang Sedang Berjuang',
    contextNote: 'Pengingat lembut bahwa Allah tidak menempatkan kemudahan setelah kesulitan, tetapi mendampingkannya bersamaan.',
    suggestedMessages: [
      'Buat kamu yang lagi capek dan berjuang, ingat ya: kemudahan itu sudah disiapkan bersamaan dengan kesulitan ini.',
      'Tetap kuat ya. Peluk hangat dari jauh, janji Allah itu pasti.',
      'Semoga hari-harimu diringankan. Jangan lupa istirahat, kamu sudah hebat.'
    ],
    audioUrl: 'https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/094.mp3'
  },
  {
    id: 'curated-duha-3-5',
    surahNumber: 93,
    surahName: 'Ad-Duha',
    surahArabic: 'الضحى',
    verseNumber: '3 - 5',
    arabicText: 'مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ ۝ وَلَلْآخِرَةُ خَيْرٌ لَكَ مِنَ الْأُولَىٰ ۝ وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ',
    translation: 'Tuhanmu tidak meninggalkanmu dan tidak (pula) membencimu. Dan sungguh, yang kemudian itu lebih baik bagimu daripada yang permulaan. Dan sungguh, kelak Tuhanmu pasti memberikan karunia-Nya kepadamu, sehingga engkau menjadi puas.',
    themeCategory: 'harapan',
    themeLabel: 'Saat Merasa Sendiri',
    contextNote: 'Ayat terindah penyejuk hati saat merasa ditinggalkan atau sedih, Allah menjanjikan masa depan yang membahagiakan.',
    suggestedMessages: [
      'Ketika kamu merasa sendiri, ingatlah Allah selalu bersamamu dan tidak pernah meninggalkanmu.',
      'Kelak Allah akan beri hadiah yang bikin kamu tersenyum lega. Sabar sebentar lagi ya.',
      'Untukmu yang kurindukan, semoga ayat ini memeluk hatimu hari ini.'
    ],
    audioUrl: 'https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/093.mp3'
  },
  {
    id: 'curated-rad-28',
    surahNumber: 13,
    surahName: "Ar-Ra'd",
    surahArabic: 'الرعد',
    verseNumber: 28,
    arabicText: 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُمْ بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    translation: '(Yaitu) orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah. Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.',
    themeCategory: 'ketenangan',
    themeLabel: 'Penenang Hati yang Gelisah',
    contextNote: 'Obat terbaik bagi jiwa yang overthinking, cemas, atau lelah dengan hiruk pikuk dunia.',
    suggestedMessages: [
      'Tarik napas perlahan... Istirahatkan pikiranmu. Semoga hatimu selalu diliputi ketenangan.',
      'Saat dunia terasa bising, kembalilah mengingat-Nya. Hatimu berharga.',
      'Semoga hari ini dan seterusnya hatimu selalu damai.'
    ],
    audioUrl: 'https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/013.mp3'
  },
  {
    id: 'curated-baqarah-286',
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    surahArabic: 'البقرة',
    verseNumber: 286,
    arabicText: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ',
    translation: 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. Dia mendapat (pahala) dari (kebajikan) yang dikerjakannya dan dia mendapat (siksa) dari (kejahatan) yang diperbuatnya.',
    themeCategory: 'ujian',
    themeLabel: 'Kuatkan Langkahmu',
    contextNote: 'Penegasan bahwa kamu dipilih menghadapi ujian ini karena Allah tahu kamu sanggup melaluinya.',
    suggestedMessages: [
      'Kamu sedang diuji karena kamu kuat. Allah tidak akan membebanimu di luar batas kemampuanmu.',
      'Percaya pada dirimu, Allah yang memilihmu karena Dia tahu kamu mampu.',
      'Satu langkah kecil hari ini sudah sangat berharga. Semangat terus ya!'
    ]
  },
  {
    id: 'curated-talaq-2-3',
    surahNumber: 65,
    surahName: 'At-Talaq',
    surahArabic: 'الطلاق',
    verseNumber: '2 - 3',
    arabicText: 'وَمَنْ يَتَّقِ اللَّهَ يَجْعَلْ لَهُ مَخْرَجًا ۝ وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ ۚ وَمَنْ يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ',
    translation: 'Barang siapa bertakwa kepada Allah niscaya Dia akan membukakan jalan keluar baginya, dan Dia memberinya rezeki dari arah yang tidak disangka-sangkanya. Dan barang siapa bertawakal kepada Allah, niscaya Allah akan mencukupkan (keperluan)nya.',
    themeCategory: 'harapan',
    themeLabel: 'Pintu Rezeki & Jalan Keluar',
    contextNote: 'Janji jalan keluar dan rezeki yang melimpah dari pintu-pintu tak terduga bagi yang berserah diri.',
    suggestedMessages: [
      'Jangan khawatirkan masa depan yang belum tiba. Cukupkan ikhtiarmu, serahkan sisanya pada Allah.',
      'Pintu rezeki dan solusi tak terduga sedang menuju ke arahmu. Tetaplah berprasangka baik.',
      'Untuk sahabatku yang sedang merintis impian, semoga dicukupkan segala urusanmu.'
    ]
  },
  {
    id: 'curated-ibrahim-7',
    surahNumber: 14,
    surahName: 'Ibrahim',
    surahArabic: 'إبراهيم',
    verseNumber: 7,
    arabicText: 'وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ ۖ وَلَئِنْ كَفَرْتُمْ إِنَّ عَذَابِي لَشَدِيدٌ',
    translation: 'Dan (ingatlah) ketika Tuhanmu memaklumkan, "Sesungguhnya jika kamu bersyukur, niscaya Aku akan menambah (nikmat) kepadamu..."',
    themeCategory: 'syukur',
    themeLabel: 'Ungkapan Rasa Syukur',
    contextNote: 'Kunci bertambahnya keberkahan hidup adalah dengan merayakan nikmat-nikmat kecil hari ini.',
    suggestedMessages: [
      'Terima kasih sudah hadir di hidupku. Aku bersyukur memiliki sosok sepertimu.',
      'Semoga hidupmu selalu dilimpahi keberkahan dan kebahagiaan yang bertambah setiap hari.',
      'Alhamdulillah untuk setiap detik kebersamaan dan kebaikan yang kita lalui.'
    ]
  },
  {
    id: 'curated-aliimran-139',
    surahNumber: 3,
    surahName: "Ali 'Imran",
    surahArabic: 'آل عمران',
    verseNumber: 139,
    arabicText: 'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنْتُمُ الْأَعْلَوْنَ إِنْ كُنْتُمْ مُؤْمِنِينَ',
    translation: 'Dan janganlah kamu (merasa) lemah, dan jangan (pula) bersedih hati, sebab kamu paling tinggi (derajatnya), jika kamu orang beriman.',
    themeCategory: 'ujian',
    themeLabel: 'Jangan Bersedih & Patah Hati',
    contextNote: 'Ayat pembangkit semangat dari kesedihan mendalam dan rasa rendah diri.',
    suggestedMessages: [
      'Tegakkan kepalamu, jangan biarkan kesedihan hari ini meredupkan cahayamu.',
      'Kesedihan ini cuma sementara, kamu jauh lebih berharga dan kuat dari yang kamu kira.',
      'Kirim doa dan semangat terbaik untukmu hari ini.'
    ]
  },
  {
    id: 'curated-furqan-74',
    surahNumber: 25,
    surahName: 'Al-Furqan',
    surahArabic: 'الفرقان',
    verseNumber: 74,
    arabicText: 'وَالَّذِينَ يَقُولُونَ رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    translation: 'Dan orang-orang yang berkata, "Ya Tuhan kami, anugerahkanlah kepada kami pasangan kami dan keturunan kami sebagai penyenang hati (kami), dan jadikanlah kami pemimpin bagi orang-orang yang bertakwa."',
    themeCategory: 'cinta',
    themeLabel: 'Doa Penyejuk Jiwa Pasangan & Keluarga',
    contextNote: 'Doa agung agar orang yang kita cintai senantiasa menjadi penyejuk mata dan hati (Qurrata A\'yun).',
    suggestedMessages: [
      'Semoga kamu selalu menjadi penyejuk hati dan kebaikan untuk sekelilingmu.',
      'Pesan ini kutulis dengan penuh doa tulus untuk keselamatan dan kebahagiaanmu.',
      'Terima kasih telah menjadi penenang di setiap langkah hariku.'
    ]
  },
  {
    id: 'curated-yusuf-86',
    surahNumber: 12,
    surahName: 'Yusuf',
    surahArabic: 'يوسف',
    verseNumber: 86,
    arabicText: 'قَالَ إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ وَأَعْلَمُ مِنَ اللَّهِ مَا لَا تَعْلَمُونَ',
    translation: 'Dia (Yakub) menjawab, "Hanya kepada Allah aku mengadukan kesusahan dan kesedihanku, dan aku mengetahui dari Allah apa yang tidak kamu ketahui."',
    themeCategory: 'ketenangan',
    themeLabel: 'Tempat Mengadu Segala Kesedihan',
    contextNote: 'Curahan hati terindah ketika tak ada manusia yang memahami beban di dadamu.',
    suggestedMessages: [
      'Jika tidak ada yang paham rasa lelahmu, ceritakan semuanya pada Allah dalam sujudmu.',
      'Hatimu aman bersama Allah. Tumpahkan segala air mata di hadapan-Nya.',
      'Semoga kelegaan segera menyelimuti jiwamu.'
    ]
  },
  {
    id: 'curated-thaha-46',
    surahNumber: 20,
    surahName: 'Thaha',
    surahArabic: 'طه',
    verseNumber: 46,
    arabicText: 'قَالَ لَا تَخَافَا ۖ إِنَّنِي مَعَكُمَا أَسْمَعُ وَأَرَىٰ',
    translation: 'Dia (Allah) berfirman, "Janganlah kamu berdua khawatir, sesungguhnya Aku bersama kamu berdua, Aku mendengar dan melihat."',
    themeCategory: 'doa',
    themeLabel: 'Jangan Takut Menghadapi Esok',
    contextNote: 'Kata-kata penenang langsung dari Allah kepada Musa dan Harun saat menghadapi ketakutan terbesar.',
    suggestedMessages: [
      'Jangan takut ya. Apapun tantangan besok, Allah bersamamu, melihat dan mendengar setiap bisik doamu.',
      'Semoga ketenangan memenuhi jiwamu malam ini. Kamu tidak sendirian.',
      'Kuatkan langkah, ada perlindungan Allah yang menyertaimu.'
    ]
  },
  {
    id: 'curated-rum-21',
    surahNumber: 30,
    surahName: 'Ar-Rum',
    surahArabic: 'الروم',
    verseNumber: 21,
    arabicText: 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَوَدَّةً وَرَحْمَةً ۚ إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِقَوْمٍ يَتَفَكَّرُونَ',
    translation: 'Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang...',
    themeCategory: 'cinta',
    themeLabel: 'Cinta, Sakinah & Kasih Sayang',
    contextNote: 'Ayat penuh kehangatan tentang ketenteraman dan cinta kasih yang dianugerahkan Allah.',
    suggestedMessages: [
      'Semoga cinta dan ketenangan selalu bersemi di antara kita.',
      'Bersamamu, hatiku menemukan tempat pulang yang tenang.',
      'Terima kasih telah menjadi berkah dan anugerah terindah dalam hidupku.'
    ]
  },
  {
    id: 'curated-ashr-1-3',
    surahNumber: 103,
    surahName: "Al-'Asr",
    surahArabic: 'العصر',
    verseNumber: '1 - 3',
    arabicText: 'وَالْعَصْرِ ۝ إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ ۝ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',
    translation: 'Demi masa. Sungguh, manusia berada dalam kerugian, kecuali orang-orang yang beriman dan mengerjakan kebajikan serta saling menasihati untuk kebenaran dan saling menasihati untuk kesabaran.',
    themeCategory: 'doa',
    themeLabel: 'Persahabatan & Saling Mengingatkan',
    contextNote: 'Pesan persahabatan sejati yang saling menggenggam tangan dalam kebaikan dan kesabaran.',
    suggestedMessages: [
      'Terima kasih selalu menjadi sahabat yang saling mengingatkan dalam kebaikan.',
      'Semoga persahabatan kita terjaga hingga ke surga-Nya.',
      'Saling mendoakan dalam diam adalah hadiah terbaik yang bisa kuberikan untukmu.'
    ]
  }
];

// Theme category pills
export const THEME_CATEGORIES = [
  { id: 'all', label: 'Semua Tema', icon: 'Sparkles' },
  { id: 'ketenangan', label: 'Ketenangan Hati', icon: 'HeartHandshake' },
  { id: 'ujian', label: 'Saat Berjuang / Ujian', icon: 'Shield' },
  { id: 'harapan', label: 'Harapan & Rezeki', icon: 'SunMedium' },
  { id: 'syukur', label: 'Rasa Syukur', icon: 'Smile' },
  { id: 'cinta', label: 'Cinta & Pasangan', icon: 'Heart' },
  { id: 'doa', label: 'Doa & Perlindungan', icon: 'HandMetal' },
];
