import { CardTheme, CardThemeId } from './types';

export const CARD_THEMES: Record<CardThemeId, CardTheme> = {
  'emerald-sand': {
    id: 'emerald-sand',
    name: 'Hening Zaitun',
    bgClass: 'bg-[#F4F4EE]',
    cardBgClass: 'bg-[#FCFCF9] border-[#E3E3D7] shadow-sm',
    borderClass: 'border-emerald-800/15',
    arabicColorClass: 'text-emerald-950',
    translationColorClass: 'text-zinc-700',
    personalMsgBgClass: 'bg-[#F2F3EC] border-[#E0E4D5] text-emerald-950',
    accentBadgeClass: 'bg-emerald-900/10 text-emerald-900 border border-emerald-900/20',
    accentGoldClass: 'text-emerald-800',
    previewColor: '#2D4A3E',
  },
  'warm-parchment': {
    id: 'warm-parchment',
    name: 'Mushaf Klasik',
    bgClass: 'bg-[#F7F3EB]',
    cardBgClass: 'bg-[#FFFDF9] border-[#EBE3D3] shadow-sm',
    borderClass: 'border-amber-900/15',
    arabicColorClass: 'text-[#2E2419]',
    translationColorClass: 'text-[#4A3E31]',
    personalMsgBgClass: 'bg-[#F6EFE0] border-[#EADFCB] text-[#3D3020]',
    accentBadgeClass: 'bg-amber-900/10 text-amber-900 border border-amber-900/20',
    accentGoldClass: 'text-[#9A7332]',
    previewColor: '#9A7332',
  },
  'pure-serenity': {
    id: 'pure-serenity',
    name: 'Putih Tenang',
    bgClass: 'bg-[#F8F9FA]',
    cardBgClass: 'bg-white border-zinc-200 shadow-sm',
    borderClass: 'border-zinc-200',
    arabicColorClass: 'text-zinc-900',
    translationColorClass: 'text-zinc-600',
    personalMsgBgClass: 'bg-zinc-50 border-zinc-200/80 text-zinc-800',
    accentBadgeClass: 'bg-zinc-100 text-zinc-800 border border-zinc-200',
    accentGoldClass: 'text-zinc-700',
    previewColor: '#52525B',
  },
  'rose-dusk': {
    id: 'rose-dusk',
    name: 'Senja Teduh',
    bgClass: 'bg-[#F9F4F2]',
    cardBgClass: 'bg-[#FDFBFB] border-[#EFE4E0] shadow-sm',
    borderClass: 'border-rose-900/15',
    arabicColorClass: 'text-[#3E2525]',
    translationColorClass: 'text-[#5C4242]',
    personalMsgBgClass: 'bg-[#F6ECE8] border-[#EDDDD7] text-[#4A2D2D]',
    accentBadgeClass: 'bg-rose-900/10 text-rose-900 border border-rose-900/20',
    accentGoldClass: 'text-[#A05C5C]',
    previewColor: '#A05C5C',
  },
  'midnight-subtle': {
    id: 'midnight-subtle',
    name: 'Malam Hening',
    bgClass: 'bg-[#18191B]',
    cardBgClass: 'bg-[#222428] border-zinc-700/60 shadow-lg',
    borderClass: 'border-zinc-700/60',
    arabicColorClass: 'text-[#F3E8CE]',
    translationColorClass: 'text-zinc-300',
    personalMsgBgClass: 'bg-[#2B2E34] border-zinc-700/80 text-[#E7DFCE]',
    accentBadgeClass: 'bg-amber-400/15 text-amber-200 border border-amber-400/30',
    accentGoldClass: 'text-amber-300',
    previewColor: '#C4A053',
  },
};
